Workaround

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -31,43 +31,29 @@ jobs:
             qemu-system-x86_64 -version
             gcc -v
       - restore_cache:
-          when:
-            condition:
-              equal: [ i386, << parameters.subarch >> ]
           keys:
-            - debian11x86
-      - restore_cache:
-          when:
-            condition:
-              equal: [ amd64, << parameters.subarch >> ]
-          keys:
-            - debian11x64
+            - debian11x86x64-<< parameters.subarch >>
       - run:
           name: "Download Debian i386"
-          when:
-            condition:
-              equal: [ i386, << parameters.subarch >> ]
           command: ".jenkins/download.sh cache debian11x86.qcow2"
       - run:
           name: "Download Debian amd64"
-          when:
-            condition:
-              equal: [ amd64, << parameters.subarch >> ]
-          command: ".jenkins/download.sh cache debian11x64.qcow2"
+          command: |
+            case "<< parameters.subarch >>" in
+            i386)
+                .jenkins/download.sh cache debian11x86.qcow2
+                ;;
+            amd64)
+                .jenkins/download.sh cache debian11x64.qcow2
+                ;;
+            *)
+                echo 'Error: unknown subarch << parameters.subarch >>'; exit 1
+                ;;
+            esac
       - save_cache:
-          when:
-            condition:
-              equal: [ i386, << parameters.subarch >> ]
-          key: debian11x86
+          key: debian11x86x64-<< parameters.subarch >>
           paths:
-            - cache/debian11x86.qcow2
-      - save_cache:
-          when:
-            condition:
-              equal: [ amd64, << parameters.subarch >> ]
-          key: debian11x64
-          paths:
-            - cache/debian11x64.qcow2
+            - cache/
       - run:
           name: "Test"
           command: |
